Repository muhammadkarbalaee/jalgorithm, pull requests merged in 2022-01, with the labels that each got.

#38 implemented bubble sort
  src/main/java/io/github/jalgorithm/algorithms/sorts/BubbleSort.java
  src/main/java/io/github/jalgorithm/algorithms/sorts/SortAlgorithm.java
  src/test/java/datastructures/ChainTable.java
  src/test/java/datastructures/DirectAddressingTableTest.java
  src/test/java/sorts/BubbleSortSample.java
  src/test/java/sorts/QuickSortSample.java
  src/test/java/sorts/SelectionSortSample.java
Labels: enhancement

#41 implemented insertion sort
  src/main/java/io/github/jalgorithm/algorithms/sorts/BubbleSort.java
  src/main/java/io/github/jalgorithm/algorithms/sorts/InsertionSort.java
  src/test/java/sorts/InsertionSortSample.java
Labels: enhancement

#46 Feature/binary search tree
  src/main/java/io/github/jalgorithm/algorithms/sorts/QuickSort.java
  src/main/java/io/github/jalgorithm/algorithms/sorts/SelectionSort.java
  src/main/java/io/github/jalgorithm/datastructures/BinarySearchTree.java
  src/main/java/io/github/jalgorithm/datastructures/trees/BinarySearchNode.java
  src/main/java/io/github/jalgorithm/datastructures/trees/BinarySearchTree.java
  src/test/java/datastructures/BinarySearchSample.java
Labels: enhancement

#48 Bug/issue#44 project structure
  build.gradle
Labels: enhancement

#64 graph is partially done
  src/main/java/io/github/jalgorithm/datastructures/graphs/Graph.java
  src/main/java/io/github/jalgorithm/datastructures/graphs/Vertex.java
  src/test/java/datastructures/GraphSample.java
Labels: enhancement

#69 fixed the issue
  src/test/java/datastructures/GraphSample.java
Labels: bug

#67 Bubble Sort : Enhancement
  src/main/java/io/github/jalgorithm/algorithms/sorts/BubbleSort.java
Labels: enhancement

#71 Create label.yml
  .github/workflows/label.yml
Labels: enhancement, management

#75 improved the selection sort algorithm
  src/main/java/io/github/jalgorithm/algorithms/sorts/SelectionSort.java
  src/test/java/sorts/SelectionSortSample.java
Labels: Implementation

#82 Enhancement/testcase fixing
  src/test/groovy/io/github/jalgorithm/algorithms/sorts/InsertionSortSpecification.groovy
  src/test/groovy/io/github/jalgorithm/algorithms/sorts/SelectionSortTest.groovy
Labels: Implementation, testing

#86 Typo fix and `reverse()`/`toString()` method implementations
  docs/javadocs/constant-values.html
  docs/javadocs/io/github/jalgorithm/datastructures/hash/ChainedHashTable.html
  docs/javadocs/io/github/jalgorithm/datastructures/hash/DirectAddressTable.html
  docs/javadocs/io/github/jalgorithm/datastructures/hash/KeyLabledObject.html
  docs/javadocs/io/github/jalgorithm/datastructures/hash/class-use/KeyLabledObject.html
  docs/javadocs/io/github/jalgorithm/datastructures/linkedlist/DoublyNode.html
  docs/javadocs/io/github/jalgorithm/datastructures/linkedlist/TailedDoublyLinkedList.html
  src/main/java/io/github/jalgorithm/datastructures/hash/ChainedHashTable.java
  src/main/java/io/github/jalgorithm/datastructures/hash/DirectAddressTable.java
  src/main/java/io/github/jalgorithm/datastructures/hash/KeyLabeledObject.java
  src/main/java/io/github/jalgorithm/datastructures/linkedlist/DoublyNode.java
  src/main/java/io/github/jalgorithm/datastructures/linkedlist/TailedDoublyLinkedList.java
  src/test/java/datastructures/ChainTable.java
  src/test/java/datastructures/DirectAddressingTableTest.java
  src/test/java/datastructures/TailedDoublyLinkedListSample.java
Labels: Implementation

#88 unidirectional tree, recursive
  src/main/java/klm/pstryk/SimpleTree.java
  src/main/java/klm/pstryk/SimpleTreeTest.java
Labels: Implementation

#92 Corrected specification for Selection sort after updated implementation
  src/test/groovy/io/github/jalgorithm/algorithms/sorts/SelectionSortTest.groovy
Labels: testing
